[09-Oct-2018 08:52:45 Europe/Berlin]   Error    404 | not found    On File C:\xampp\htdocs\Core\Router.php  At Line 84   Stack Trace :  #0 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/favicon.ico')
#1 {main} 
[09-Oct-2018 09:03:34 Europe/Berlin]   Error    Undefined index: id    On File C:\xampp\htdocs\App\Controllers\APIController.php  At Line 17   Stack Trace :  #0 C:\xampp\htdocs\App\Controllers\APIController.php(17): Core\Error::errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 17, Array)
#1 [internal function]: App\Controllers\APIController->index('31')
#2 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success/api/31')
#4 {main} 
[09-Oct-2018 09:04:31 Europe/Berlin]   Error    Undefined offset: 31    On File C:\xampp\htdocs\App\Controllers\APIController.php  At Line 17   Stack Trace :  #0 C:\xampp\htdocs\App\Controllers\APIController.php(17): Core\Error::errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 17, Array)
#1 [internal function]: App\Controllers\APIController->index('31')
#2 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success/api/31')
#4 {main} 
[09-Oct-2018 09:05:07 Europe/Berlin]   Error    Undefined offset: 31    On File C:\xampp\htdocs\App\Controllers\APIController.php  At Line 17   Stack Trace :  #0 C:\xampp\htdocs\App\Controllers\APIController.php(17): Core\Error::errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 17, Array)
#1 [internal function]: App\Controllers\APIController->index('31')
#2 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success/api/31')
#4 {main} 
[09-Oct-2018 09:05:10 Europe/Berlin]   Error    Undefined offset: 31    On File C:\xampp\htdocs\App\Controllers\APIController.php  At Line 17   Stack Trace :  #0 C:\xampp\htdocs\App\Controllers\APIController.php(17): Core\Error::errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 17, Array)
#1 [internal function]: App\Controllers\APIController->index('31')
#2 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success/api/31')
#4 {main} 
[09-Oct-2018 09:07:52 Europe/Berlin]   Error    Header may not contain more than a single header, new line detected    On File C:\xampp\htdocs\App\helpers.php  At Line 4   Stack Trace :  #0 [internal function]: Core\Error::errorHandler(2, 'Header may not ...', 'C:\\xampp\\htdocs...', 4, Array)
#1 C:\xampp\htdocs\App\helpers.php(4): header('location:https:...')
#2 C:\xampp\htdocs\App\Controllers\APIController.php(19): redirect('https://37f32cl...')
#3 [internal function]: App\Controllers\APIController->index('31')
#4 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success/api/31')
#6 {main} 
[09-Oct-2018 09:08:17 Europe/Berlin]   Error    Header may not contain more than a single header, new line detected    On File C:\xampp\htdocs\App\helpers.php  At Line 4   Stack Trace :  #0 [internal function]: Core\Error::errorHandler(2, 'Header may not ...', 'C:\\xampp\\htdocs...', 4, Array)
#1 C:\xampp\htdocs\App\helpers.php(4): header('location:https:...')
#2 C:\xampp\htdocs\App\Controllers\APIController.php(19): redirect('https://37f32cl...')
#3 [internal function]: App\Controllers\APIController->index('31')
#4 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success/api/31')
#6 {main} 
[09-Oct-2018 10:14:21 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 27   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success')
#11 {main} 
[09-Oct-2018 10:14:24 Europe/Berlin]   Error    Parse error: syntax error, unexpected ';', expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 27   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success')
#11 {main} 
[09-Oct-2018 10:14:58 Europe/Berlin]   Error    Parse error: syntax error, unexpected 'echo' (T_ECHO), expecting ',' or ')' (View: C:\xampp\htdocs\App\Views\success.blade.php)    On File C:\xampp\htdocs\storage\views\cf42f856478f572a200f7e15ac6cb2921760be86.php  At Line 27   Stack Trace :  #0 C:\xampp\htdocs\vendor\illuminate\view\Engines\PhpEngine.php(46): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 C:\xampp\htdocs\vendor\illuminate\view\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\view\View.php(137): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array)
#3 C:\xampp\htdocs\vendor\illuminate\view\View.php(120): Illuminate\View\View->getContents()
#4 C:\xampp\htdocs\vendor\illuminate\view\View.php(85): Illuminate\View\View->renderContents()
#5 C:\xampp\htdocs\Core\View.php(13): Illuminate\View\View->render()
#6 C:\xampp\htdocs\App\helpers.php(29): Core\View::render('success', Array)
#7 C:\xampp\htdocs\App\Controllers\SuccessController.php(16): view('success')
#8 [internal function]: App\Controllers\SuccessController->index()
#9 C:\xampp\htdocs\Core\Router.php(72): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\public\index.php(41): Core\Router->dispatch('/success')
#11 {main} 
